GET http://localhost:3000/api/artists
###
POST http://localhost:3000/api/artists
Content-Type: application/json

{
    "artist_name":"Sultan",
    "bio":"Programmer",
    "genre":"Hip-Hop"
}
###
DELETE http://localhost:3000/api/artists/69b76336e6b2a09487d8892a

