import Image from "../src/Images/justin1.jpg"
export const  Data =[
    {
      id:1,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    },
      {
        id:12,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    },
      {
        id:2,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    },
      {
        id:4,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    },
      {
        id:5,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    },
      {
        id:6,
        name:"Sultan",
        Genre:"Afro",
        Total:345,
        Sign:"May,02,2025",
        Image
    }
]
// export default Data